# Generated by Django 5.2.14 on 2026-08-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["post", "created_at"], name="comment_post_created_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                condition=models.Q(("is_published", True)),
                fields=["-created_at"],
                name="post_published_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="user_email_idx"),
        ),
    ]
