# Generated by Django 5.2.14 on 2026-08-06 17:28

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment_comment_post_created_idx_and_more"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    models.F("title"), name="gin_trgm_ops"
                ),
                condition=models.Q(("is_published", True)),
                name="post_title_trgm_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    models.F("body"), name="gin_trgm_ops"
                ),
                condition=models.Q(("is_published", True)),
                name="post_body_trgm_idx",
            ),
        ),
    ]
